// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8BbLHCIPPt5vxwJes9vlw995tfMk5P4',
    appId: '1:407297767098:web:dcf1e7d71b238a95d3f483',
    messagingSenderId: '407297767098',
    projectId: 'musmeramedya',
    authDomain: 'musmeramedya.firebaseapp.com',
    storageBucket: 'musmeramedya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnR2Pe1VwMX9yIuLZPNSW9KcQQL6jCGwU',
    appId: '1:407297767098:android:13795aaa404058c0d3f483',
    messagingSenderId: '407297767098',
    projectId: 'musmeramedya',
    storageBucket: 'musmeramedya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClNg1GXbWr4Hla7-ep3sf2gJKDbJL5g5c',
    appId: '1:407297767098:ios:b8e470d5c774ed78d3f483',
    messagingSenderId: '407297767098',
    projectId: 'musmeramedya',
    storageBucket: 'musmeramedya.appspot.com',
    iosBundleId: 'com.guzelsoftware.musmeramedya',
  );
}
